"""
FlowScroll 常量配置。
集中管理项目中的魔法数字和通用配置。
"""

# 滚动引擎相关常量
ENGINE_TICK_INTERVAL = 0.004  # 4ms，与系统滚动事件同步
ENGINE_IDLE_POLL_INTERVAL = 0.05  # 50ms
INERTIA_STOP_THRESHOLD = 0.001
SCROLL_HISTORY_WINDOW = 0.1  # 100ms

# 输入监听相关常量
DOUBLE_CLICK_THRESHOLD = 0.15  # 150ms

# 窗口监控相关常量
WINDOW_MONITOR_START_DELAY = 2.0
WINDOW_MONITOR_POLL_INTERVAL = 0.5
WINDOW_INFO_FAILURE_STALE_THRESHOLD = 3

# 配置相关常量
CONFIG_VERSION = 3
DEFAULT_INERTIA_FRICTION_MS = 500
INERTIA_FRICTION_MIN_MS = 100
INERTIA_FRICTION_MAX_MS = 3000
DEFAULT_INERTIA_THRESHOLD = 80.0
INERTIA_THRESHOLD_MIN = 30.0
INERTIA_THRESHOLD_MAX = 300.0

# 平台相关常量
WINDOWS_SCROLL_MULTIPLIER = 0.00005
MACOS_SCROLL_MULTIPLIER = 0.0001
DEFAULT_SCROLL_MULTIPLIER = 0.00005

# UI 相关常量
OVERLAY_PREVIEW_DURATION = 800
DEFAULT_OVERLAY_SIZE = 60.0
MAIN_WINDOW_MIN_WIDTH = 420
MAIN_WINDOW_MIN_HEIGHT = 680
MAIN_WINDOW_DEFAULT_WIDTH = 650
MAIN_WINDOW_DEFAULT_HEIGHT = 720
WORK_MODE_DIALOG_WIDTH = 520
WORK_MODE_DIALOG_HEIGHT = 620
INERTIA_DIALOG_WIDTH = 460
INERTIA_DIALOG_HEIGHT = 420
REVERSE_DIALOG_WIDTH = 400
REVERSE_DIALOG_HEIGHT = 240
WEBDAV_DIALOG_DEFAULT_WIDTH = 500
WEBDAV_DIALOG_DEFAULT_HEIGHT = 320
WEBDAV_DIALOG_MIN_WIDTH = 500
WEBDAV_DIALOG_MIN_HEIGHT = 320
SLIDER_DEFAULT_HEIGHT = 24
SPINBOX_WIDTH = 70
SPINBOX_HEIGHT = 32

# 更新检查相关常量
UPDATE_CHECK_TIMEOUT = 5
